take a Packages file instead of looking for specific ones

diff --git a/configure-rosdep b/configure-rosdep
--- a/configure-rosdep
+++ b/configure-rosdep
@@ -28,8 +28,12 @@ cleanup() {
 
 usage() {
     cat <<EOF
-Usage: $(basename ${this})
-Configure rosdistro to use additional repositories.
+Usage: $(basename ${this}) [OPTION]... PACKAGES_URL
+Trick rosdep into using additional apt packages.
+
+Options:
+
+    -h                 print usage and exit
 
 Examples:
 
@@ -44,41 +48,72 @@ export TMPDIR="${tmpdir}"
 export LC_ALL=C
 
 if ! [ 0 -eq "$(id -u)" ]; then
-    sudo "${this}"
+    sudo "${this}" $@
     exit "$?"
 fi
 
+# while getopts ":hA:D:" opt; do
 while getopts ":h" opt; do
     case "${opt}" in
         h)
             usage
             exit 0
             ;;
+        # A) readonly architecture="${OPTARG}" ;;
+        # D) readonly distribution="${OPTARG}" ;;
         :) die "missing argument: -${OPTARG}" ;;
         \?) die "bad option: -${OPTARG}" ;;
     esac
 done
 shift "$((${OPTIND} - 1))"
 
-info "discovering realsense packages"
-readonly realsense_package_list="$(mktemp -t realsense.package.list.XXXXXX)"
-find /var/lib/apt/lists -type f \
-     -a \( -name 'realsense*_Packages'     -exec cat       {} \; \) \
-     -o \( -name 'realsense*_Packages.bz2' -exec bzip2 -dc {} \; \) \
-     -o \( -name 'realsense*_Packages.gz'  -exec gzip  -dc {} \; \) \
-     -o \( -name 'realsense*_Packages.lz4' -exec lz4   -dc {} \; \) \
-     -o \( -name 'realsense*_Packages.xz'  -exec xz    -dc {} \; \) \
-    | sed -nr 's|^Package:[[:space:]]+([[:graph:]]+).*$|\1|gp' \
-          >"${realsense_package_list}"
-sort -uo "${realsense_package_list}" "${realsense_package_list}"
+if ! [ 1 -eq "$#" ]; then
+    die "bad args"
+fi
 
-readonly realsense_yaml="/var/rosdep/realsense.yaml"
-info "generating ${realsense_yaml}"
-mkdir -vp "$(dirname "${realsense_yaml}")"
-cat >"${realsense_yaml}" <<EOF
-# ${realsense_yaml}
+# TODO: take (or discover) InRelease URL, OS distribution, architecture;
+# discover/download the relevant Packages file(s), check hashes thereon,
+# uncompress, etc...
 #
-# THIS IS A GENERATED FILE
+# https://wiki.debian.org/DebianRepository/Format
+
+# if ! [ -n "${architecture:-}" ]; then
+#     warning "unspecified architecture"
+#     if ! command -v uname >/dev/null 2>&1; then
+#         die "missing program: uname"
+#     fi
+#     readonly architecture="$(uname -m)"
+#     warning "detected architecture: ${architecture}"
+# fi
+
+# if ! [ -n "${distribution:-}" ]; then
+#     warning "unspecified distribution"
+#     if ! command -v lsb_release >/dev/null 2>&1; then
+#         die "missing program: lsb_release"
+#     fi
+#     readonly distribution="$(lsb_release -sc)"
+#     warning "detected distribution: ${distribution}"
+# fi
+
+readonly packages_url="$1"
+readonly packages="${tmpdir}/$(echo "${packages_url}" | tr -s '/' '_')"
+readonly pkgname_list="${packages}.list"
+curl -fsSLo "${packages}" "${packages_url}"
+sed -nr 's|^Package:[[:space:]]+([[:graph:]]+).*$|\1|gp' <"${packages}" >"${pkgname_list}"
+sort -uo "${pkgname_list}" "${pkgname_list}"
+
+# Generate a "rosdep yaml" file that declares an eponymous ROS package package
+# for each apt package listed in the Packages file.
+readonly rosdep_yaml="/var/lib/rosdep/$(basename "${packages}").yaml"
+info "generating ${rosdep_yaml}"
+mkdir -vp "$(dirname "${rosdep_yaml}")"
+cat >"${rosdep_yaml}" <<EOF
+# ${rosdep_yaml}
+#
+# This is a generated rosdep yaml file.
+#
+# https://docs.ros.org/independent/api/rosdep/html/rosdep_yaml_format.html
+#
 # generator : ${this}
 # user      : $(id)
 # uname     : $(uname -a)
@@ -86,24 +121,29 @@ cat >"${realsense_yaml}" <<EOF
 
 EOF
 
-while read realsense_package; do
-    cat >>"${realsense_yaml}" <<EOF
-${realsense_package}:
-  ubuntu: [${realsense_package}]
+while read pkgname; do
+    cat >>"${rosdep_yaml}" <<EOF
+${pkgname}:
+  ubuntu: [${pkgname}]
 EOF
-done <"${realsense_package_list}"
+done <"${pkgname_list}"
 
-readonly realsense_list="/etc/ros/rosdep/sources.list.d/00-realsense.list"
-info "generating ${realsense_list}"
-mkdir -vp "$(dirname "${realsense_list}")"
-cat >"${realsense_list}" <<EOF
-# ${realsense_list}
+# Generate a "rosdep sources list" file that references the freshly-generated
+# rosdep yaml.
+readonly rosdep_sources_list="/etc/ros/rosdep/sources.list.d/$(basename "${packages}").list"
+info "generating ${rosdep_sources_list}"
+mkdir -vp "$(dirname "${rosdep_sources_list}")"
+cat >"${rosdep_sources_list}" <<EOF
+# ${rosdep_sources_list}
 #
-# THIS IS A GENERATED FILE
+# This is a generated rosdep sources list file.
+#
+# https://docs.ros.org/independent/api/rosdep/html/sources_list.html
+#
 # generator : ${this}
 # user      : $(id)
 # uname     : $(uname -a)
 # date      : $(date -u +"%Y-%m-%dT%H:%M:%SZ")
 
-yaml file://${realsense_yaml}
+yaml file://${rosdep_yaml}
 EOF
