ed docker-catkin: some shellcheck fixes

diff --git a/docker-catkin b/docker-catkin
--- a/docker-catkin
+++ b/docker-catkin
@@ -9,22 +9,19 @@ readonly here="$(dirname "${this}")"
 readonly whatami="$(basename "${this}")"
 readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
 
-readonly default_distribution="xenial"
-readonly default_ros_distro="kinetic"
-
-log() { echo "${whatami}[$$]: $@" >&2; }
-error() { log "ERROR: $@"; }
-warning() { log "WARNING: $@"; }
-info() { log "INFO: $@"; }
+log() { echo "${whatami}[$$]: $*" >&2; }
+error() { log "ERROR: $*"; }
+warning() { log "WARNING: $*"; }
+info() { log "INFO: $*"; }
 
 die() {
-    error "$@"
+    error "$*"
     usage >&2
     exit 1
 }
 
 cleanup() {
-    local status="$?"
+    status="$?"
     rm -rf "${tmpdir}"
     if command -v docker >/dev/null 2>&1; then
         docker system prune --force --filter until=6h >&2 || true
@@ -149,7 +146,9 @@ dircopy() {
 # $1 : source directory
 # $2 : target directory
 catkin_ws_pathfix() {
+    # shellcheck disable=SC2039
     local source_dir="$1"
+    # shellcheck disable=SC2039
     local target_dir="$2"
     find \
         "${target_dir}/.catkin_tools" \
@@ -168,7 +167,7 @@ catkin_ws_pathfix() {
 is_in_container() { grep -q 'lxc\|docker' /proc/1/cgroup; }
 
 catkin_verb() {
-    catkin $@ \
+    catkin "$@" \
         --no-color \
         --no-notify \
         --no-status \
@@ -192,6 +191,7 @@ catkin_verb() {
 # take catkin_ws and vet it; for good catkin_ws, print it and return success;
 # otherwise, print nothing and return failure
 vet_catkin_ws() {
+    # shellcheck disable=SC2039
     local result=""
     if ! result="$(readlink -f "$1")"; then
         error "bad path: $1"
@@ -210,6 +210,7 @@ vet_catkin_ws() {
 }
 
 vet_root_script() {
+    # shellcheck disable=SC2039
     local result=""
     if ! result="$(readlink -f "$1")"; then
         error "bad path: $1"
@@ -250,7 +251,7 @@ while getopts ":hC:D:R:" opt; do
         \?) die "bad option: -${OPTARG}" ;;
     esac
 done
-shift "$((${OPTIND} - 1))"
+shift "$((OPTIND - 1))"
 
 # distribution
 if [ -n "${distribution:-}" ]; then
@@ -294,8 +295,6 @@ fi
 readonly copy_catkin_ws="$(mktemp -dt copy_catkin_ws.XXXXXX)"
 dircopy "${catkin_ws}" "${copy_catkin_ws}"
 
-# https://stackoverflow.com/questions/23513045/how-to-check-if-a-process-is-running-inside-docker-container
-# https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker
 if ! is_in_container; then
     # We build stuff under $TMPDIR. Sometimes, the build requires the
     # extraction of tarballs. Extracting tarballs on OverlayFS is, apparently,
@@ -435,6 +434,7 @@ result=""
     # because ROS stupidly expands undefined variables, but we still need to
     # collect test results failures
     set +eu
+    # shellcheck disable=SC1090
     . "/opt/ros/${ros_distro}/setup.sh"
     catkin_test_results "${copy_catkin_ws}"
 ) && result="$?" || result="$?"
