wip: freeze-rosdep

diff --git a/freeze-rosdep b/freeze-rosdep
--- a/freeze-rosdep
+++ b/freeze-rosdep
@@ -9,6 +9,8 @@ readonly here="$(dirname "${this}")"
 readonly whatami="$(basename "${this}")"
 readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
 
+readonly default_destdir="/var/lib/rosdep"
+
 log() { echo "${whatami}[$$]: $@" >&2; }
 error() { log "ERROR: $@"; }
 warning() { log "WARNING: $@"; }
@@ -33,11 +35,14 @@ Cache rosdistro yamls and force rosdep to use them.
 
 Options:
 
-    -h    print usage and exit
+    -h            print usage and exit
+    -t DESTDIR    download files to DESTDIR (default: ${default_destdir})
 
 Examples:
 
     \$ $0 /etc/ros/rosdep/sources.list.d/20-default.list
+
+    \$ $0 -t /tmp /etc/ros/rosdep/sources.list.d/20-default.list
 
 EOF
 }
@@ -49,6 +54,24 @@ filenamify() {
     # printf "$@" | base64 -w0
 }
 
+# $1 : http uri
+# $2 : destination directory (default /var/lib/rosdep)
+#
+# Download given rosdep yaml http uri to (optionally given) destination
+# directory. On success, print full path to downloaded file. On failure, print
+# nothing.
+dl_rosdep() {
+    local http_uri="$1"
+    local dest_dir="${2:-/var/lib/rosdep}"
+    local output="${dest_dir}/$(filenamify "${http_uri}")"
+    if ! curl --create-dirs -fsSLo "${output}" "${http_uri}"; then
+        error "FAILURE: curl --create-dirs -fsSLo ${output} ${http_uri}"
+        return 1
+    fi
+    echo "${output}"
+    return 0
+}
+
 ################################################################################
 
 trap cleanup EXIT
@@ -56,12 +79,13 @@ export TMPDIR="${tmpdir}"
 export LC_ALL=C
 
 # while getopts ":hA:D:" opt; do
-while getopts ":h" opt; do
+while getopts ":ht:" opt; do
     case "${opt}" in
         h)
             usage
             exit 0
             ;;
+        t) readonly destdir="${OPTARG}" ;;
         :) die "missing argument: -${OPTARG}" ;;
         \?) die "bad option: -${OPTARG}" ;;
     esac
@@ -81,14 +105,21 @@ if ! [ -f "${rosdep_list}" ]; then
     die "bad file: ${rosdep_list}"
 fi
 
+if [ -n "${destdir:-}" ]; then
+    info "destdir: ${destdir}"
+else
+    readonly destdir="${default_destdir}"
+    warning "defaulting destdir: ${destdir}"
+fi
+
 readonly http_uri_list="$(mktemp -t http_uri_list.XXXXXX)"
 sed -nr 's/^(gbpdistro|yaml) (http[[:graph:]]+)(.*)$/\2/gp' <"${rosdep_list}" >"${http_uri_list}"
 sort -uo "${http_uri_list}" "${http_uri_list}"
 
 while read http_uri; do
-    file_uri="file:///var/lib/rosdep/$(filenamify "${http_uri}")"
-    curl --fail --silent --location --create-dirs --output "${file_uri#file://}" "${http_uri}"
-    sed -i "s|${http_uri}|${file_uri}|g" "${rosdep_list}"
+    output="${destdir}/$(filenamify "${http_uri}")"
+    curl --create-dirs -fsSLo "${output}" "${http_uri}"
+    sed -i "s|${http_uri}|file://${output}|g" "${rosdep_list}"
 done <"${http_uri_list}"
 
 exit "$?"
