git2origtar shellcheck fixes

diff --git a/git2origtar b/git2origtar
--- a/git2origtar
+++ b/git2origtar
@@ -5,17 +5,16 @@
 set -eu
 
 readonly this="$(readlink -f "$0")"
-readonly here="$(dirname "${this}")"
 readonly whatami="$(basename "${this}")"
 readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
 
-log() { echo "${whatami}[$$]: $@" >&2; }
-error() { log "ERROR: $@"; }
-warning() { log "WARNING: $@"; }
-info() { log "INFO: $@"; }
+log() { echo "${whatami}[$$]: $*" >&2; }
+error() { log "ERROR: $*"; }
+warning() { log "WARNING: $*"; }
+info() { log "INFO: $*"; }
 
 die() {
-    error "$@"
+    error "$*"
     usage >&2
     exit 1
 }
@@ -88,7 +87,7 @@ gitcopy() {
 #
 # --- https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-source
 is_good_package_name() {
-    echo $@ | grep -Eq '^[a-z0-9][a-z0-9.+-]+$'
+    echo "$@" | grep -Eq '^[a-z0-9][a-z0-9.+-]+$'
 }
 
 vet_package_name() {
@@ -106,7 +105,7 @@ infer_package_name() {
 }
 
 is_good_version() {
-    echo $@ | grep -Eq '^[[:digit:]]+[.][[:digit:]]+[.][[:digit:]]+[-][[:digit:]]+[-]g[[:xdigit:]]{7,40}$'
+    echo "$@" | grep -Eq '^[[:digit:]]+[.][[:digit:]]+[.][[:digit:]]+[-][[:digit:]]+[-]g[[:xdigit:]]{7,40}$'
 }
 
 vet_version() {
@@ -124,6 +123,7 @@ infer_version() {
 }
 
 vet_workdir() {
+    # shellcheck disable=SC2039
     local result=""
     if ! result="$(readlink -f "$1")"; then
         error "bad path: $1"
@@ -146,6 +146,7 @@ vet_workdir() {
 }
 
 vet_outfile() {
+    # shellcheck disable=SC2039
     local result=""
     if ! result="$(readlink -f "$1")"; then
         error "bad path: $1"
@@ -164,6 +165,7 @@ vet_outfile() {
 }
 
 vet_mtime() {
+    # shellcheck disable=SC2039
     local result=""
     if ! result="@$(date -d "$1" +%s)"; then
         error "bad mtime: $1"
@@ -209,7 +211,7 @@ while getopts ":hfC:P:V:o:" opt; do
         \?) die "Invalid option: -${OPTARG}" ;;
     esac
 done
-shift "$((${OPTIND} - 1))"
+shift "$((OPTIND - 1))"
 
 # workdir
 if [ -n "${workdir:-}" ]; then
