ed git2origtar
git show unix timestamp

shellcheck fixes

delete obsolete vet_mtime

diff --git a/git2origtar b/git2origtar
--- a/git2origtar
+++ b/git2origtar
@@ -4,9 +4,12 @@
 
 set -eu
 
-readonly this="$(readlink -f "$0")"
-readonly whatami="$(basename "${this}")"
-readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
+this="$(readlink -f "$0")"
+readonly this="${this}"
+whatami="$(basename "${this}")"
+readonly whatami="${whatami}"
+tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
+readonly tmpdir="${tmpdir}"
 
 log() { echo "${whatami}[$$]: $*" >&2; }
 error() { log "ERROR: $*"; }
@@ -126,6 +129,7 @@ infer_version() {
 
 vet_workdir() {
     # shellcheck disable=SC2039
+    # shellcheck disable=SC3043
     local result=""
     if ! result="$(readlink -f "$1")"; then
         error "bad path: $1"
@@ -149,6 +153,7 @@ vet_workdir() {
 
 vet_outfile() {
     # shellcheck disable=SC2039
+    # shellcheck disable=SC3043
     local result=""
     if ! result="$(readlink -f "$1")"; then
         error "bad path: $1"
@@ -161,17 +166,6 @@ vet_outfile() {
         fi
         warning "extant file: ${result}"
         warning "$(rm -v "${result}")"
-    fi
-    echo "${result}"
-    return 0
-}
-
-vet_mtime() {
-    # shellcheck disable=SC2039
-    local result=""
-    if ! result="@$(date -d "$1" +%s)"; then
-        error "bad mtime: $1"
-        return 1
     fi
     echo "${result}"
     return 0
@@ -264,9 +258,8 @@ if [ -f "${outfile}" ]; then
 fi
 
 # mtime
-mtime="$(git -C "${workdir}" show -s --format=%ci HEAD)"
-if ! mtime="$(vet_mtime "${mtime}")"; then
-    die "FAILURE: vet_mtime ${mtime}"
+if ! mtime="@$(git -C "${workdir}" show -s --format=%ct HEAD)"; then
+    die "FAILURE: git -C ${workdir} show -s --format=%ct HEAD"
 fi
 readonly mtime="${mtime}"
 info "mtime: ${mtime} ($(date -uIs -d "${mtime}"))"
