de-function (build|run)_megadeb

diff --git a/mkmegadeb b/mkmegadeb
--- a/mkmegadeb
+++ b/mkmegadeb
@@ -129,129 +129,6 @@ apt_uninstall() {
         | xargs -r apt-get -yqo APT::Sandbox::User="$(whoami)" remove
 }
 
-run_megadeb() {
-    if ! [ "true" = "${requested_uninstall:-false}" ]; then
-        if [ -x "${here}/hooks/preinst" ]; then
-            "${here}/hooks/preinst"
-        fi
-    fi
-
-    # vet the archive directory
-    if ! [ -f "${here}/Packages" ]; then
-        error "missing file: ${here}/Packages"
-        return 1
-    fi
-
-    info "creating temporary apt configuration"
-    enfake_apt "$(mktemp -dt fake_apt_dir.XXXXXX)"
-
-    # TODO(neil): How should we treat the capability of installing "everything"
-    # from the Megadeb?
-    #
-    # First, it's not _really_ everything, since we stop traversing the
-    # recursive dependencies at the "bootstrap boundary"; i.e., those packages
-    # that either comprise dependency cycles (e.g. libc) or depend on udebs
-    # (Debian installer packages).
-    #
-    # Second, having _almost_ everything works great --- right up until, say,
-    # Canonical bumps the version of a certain package _beyond_ the bootstrap
-    # boundary; a certain package that we depended on via a version equivalence
-    # relationship. This situation is untenable because the dependency we
-    # "knew" we needed (A) we didn't pack because we couldn't and (B) Canonical
-    # stopped providing the specific version.
-    #
-    # The benefit to relying on the default apt lists is that, as our
-    # dependencies age out of existence, we can recover by leaning on the newer
-    # versions that we didn't bring with us. The drawback is that the megadebs
-    # are not truly "stand-alone" -- at least not in the same way that Debian
-    # installers are.
-    if [ "true" = "${requested_selfonly:-false}" ]; then
-        # remove old apt sources list files
-        warning "running self-contained (without external packages)"
-        find "$(etc_apt)" -type f -name '*.list' -print -delete
-        find "$(var_lib_apt_lists)" -type f -print -delete
-    fi
-
-    # install new apt sources list file
-    cat >"$(etc_apt_sources_list_d)/$(echo "${here}" | tr -s '/' '_').list" <<EOF
-deb [trusted=yes] file://${here} ./
-EOF
-
-    # update apt to make it aware of the new fake repo
-    apt-get -yqo APT::Sandbox::User="$(whoami)" update
-
-    local top_pkg_list="$(mktemp -t top_pkg_list.XXXXXX)"
-    find "${here}" -maxdepth 1 -type f -name '*.deb' \
-        -exec dpkg-deb --show --showformat='${Package}\n' {} \; \
-        >"${top_pkg_list}"
-    if ! [ "true" = "${requested_uninstall:-false}" ]; then
-        info "installing packages"
-        if [ -f "${here}/install-list.txt" ]; then
-            apt_install "${here}/install-list.txt"
-        else
-            apt_install "${top_pkg_list}"
-        fi
-    else
-        info "uninstalling packages"
-        if [ -f "${here}/uninstall-list.txt" ]; then
-            apt_uninstall "${here}/uninstall-list.txt"
-        else
-            apt_uninstall "${top_pkg_list}"
-        fi
-    fi
-
-    if ! [ "true" = "${requested_uninstall:-false}" ]; then
-        if [ -x "${here}/hooks/postinst" ]; then
-            "${here}/hooks/postinst"
-        fi
-    fi
-}
-
-build_megadeb() {
-    if [ "true" = "${repolize:-false}" ]; then
-        "${here}/repolizer" -C "${workdir}" -D "${distribution}"
-    fi
-
-    # create and populate makeself archive dir
-    readonly makeself_archive_dir="$(mktemp -dt makeself_archive_dir.XXXXXX)"
-    tar -C "${workdir}" -cf- . | tar -C "${makeself_archive_dir}" -xf-
-    cp -v "${this}" "${makeself_archive_dir}/$(basename "${this}")"
-
-    if [ -n "${makeself_file_name:-}" ]; then
-        info "makeself_file_name: ${makeself_file_name}"
-    else
-        readonly makeself_file_name="${workdir}.deb.run"
-        warning "defaulting makeself_file_name: ${makeself_file_name}"
-    fi
-
-    readonly help_header_file="$(mktemp -t help_header_file.XXXXXX)"
-    (
-        export product_name
-        export makeself_basename="$(basename "${makeself_file_name}")"
-        envsubst '${product_name},${makeself_basename}' >"${help_header_file}" <<'EOF'
-Usage: ./${makeself_basename} [MAKESELF_OPTION]... -- [SCRIPT_OPTION]...
-Install ${product_name} packages and dependencies.
-
-Script Options:
-
-    -u    uninstall
-    -s    run self-contained (without external packages)
-
-Makeself Options:
-EOF
-    )
-
-    # note the (undocumented) trailing `-r` option; this is what causes the
-    # self-extracting archive to invoke this script's `run_megadeb` function
-    "${here}/mkself" \
-        --nocomp --sha256 \
-        --help-header "${help_header_file}" \
-        "${makeself_archive_dir}" \
-        "${makeself_file_name}" \
-        "MegaDeb" \
-        "./$(basename "${this}")" -r
-}
-
 ################################################################################
 
 trap cleanup EXIT
@@ -312,10 +189,147 @@ else
     warning "defaulting product_name: ${product_name}"
 fi
 
-if [ "true" = "${run_megadeb:-false}" ]; then
-    run_megadeb
+################################################################################
+
+if ! [ "true" = "${run_megadeb:-false}" ]; then
+    # Let's Build the Megadeb.(tm)
+    if [ "true" = "${repolize:-false}" ]; then
+        "${here}/repolizer" -C "${workdir}" -D "${distribution}"
+    fi
+
+    # create and populate makeself archive dir
+    readonly makeself_archive_dir="$(mktemp -dt makeself_archive_dir.XXXXXX)"
+    tar -C "${workdir}" -cf- . | tar -C "${makeself_archive_dir}" -xf-
+    # copy self to top of makeself archive dir
+    cp -v "${this}" "${makeself_archive_dir}/$(basename "${this}")"
+
+    if [ -n "${makeself_file_name:-}" ]; then
+        info "makeself_file_name: ${makeself_file_name}"
+    else
+        readonly makeself_file_name="${workdir}.deb.run"
+        warning "defaulting makeself_file_name: ${makeself_file_name}"
+    fi
+
+    readonly help_header_file="$(mktemp -t help_header_file.XXXXXX)"
+    (
+        export product_name
+        export makeself_basename="$(basename "${makeself_file_name}")"
+        envsubst '${product_name},${makeself_basename}' >"${help_header_file}" <<'EOF'
+Usage: ./${makeself_basename} [MAKESELF_OPTION]... -- [SCRIPT_OPTION]...
+Install ${product_name} packages and dependencies.
+
+Script Options:
+
+    -u    uninstall
+    -s    run self-contained (without external packages)
+
+Makeself Options:
+EOF
+    )
+
+    # note the (undocumented) trailing `-r` option; this is what causes the
+    # self-extracting archive to invoke this script's `run_megadeb` function
+    "${here}/mkself" \
+        --nocomp --sha256 \
+        --help-header "${help_header_file}" \
+        "${makeself_archive_dir}" \
+        "${makeself_file_name}" \
+        "MegaDeb" \
+        "./$(basename "${this}")" -r
+
+    exit "$?"
+fi
+
+################################################################################
+
+# Let's Run the Megadeb.(tm)
+
+###########
+# WARNING #
+###########
+#
+################################################################################
+# The nature of "${here}" is different! _BUILDING_ the megadeb copies `${this}`
+# to the top of the makeself archive dir and specifies `${this} -r` as the
+# entrypoint command. Therefore, in the _RUNNING_ context, `${here}` is
+# synonymous with what makeself calls the `--target`; i.e., the directory to
+# which the archive self-extracts (usually a temporary directory).
+################################################################################
+
+if ! [ "true" = "${requested_uninstall:-false}" ]; then
+    if [ -x "${here}/hooks/preinst" ]; then
+        "${here}/hooks/preinst"
+    fi
+fi
+
+# vet the archive directory
+if ! [ -f "${here}/Packages" ]; then
+    error "missing file: ${here}/Packages"
+    return 1
+fi
+
+info "creating temporary apt configuration"
+enfake_apt "$(mktemp -dt fake_apt_dir.XXXXXX)"
+
+# TODO(neil): How should we treat the capability of installing "everything"
+# from the Megadeb?
+#
+# First, it's not _really_ everything, since we stop traversing the
+# recursive dependencies at the "bootstrap boundary"; i.e., those packages
+# that either comprise dependency cycles (e.g. libc) or depend on udebs
+# (Debian installer packages).
+#
+# Second, having _almost_ everything works great --- right up until, say,
+# Canonical bumps the version of a certain package _beyond_ the bootstrap
+# boundary; a certain package that we depended on via a version equivalence
+# relationship. This situation is untenable because the dependency we
+# "knew" we needed (A) we didn't pack because we couldn't and (B) Canonical
+# stopped providing the specific version.
+#
+# The benefit to relying on the default apt lists is that, as our
+# dependencies age out of existence, we can recover by leaning on the newer
+# versions that we didn't bring with us. The drawback is that the megadebs
+# are not truly "stand-alone" -- at least not in the same way that Debian
+# installers are.
+if [ "true" = "${requested_selfonly:-false}" ]; then
+    # remove old apt sources list files
+    warning "running self-contained (without external packages)"
+    find "$(etc_apt)" -type f -name '*.list' -print -delete
+    find "$(var_lib_apt_lists)" -type f -print -delete
+fi
+
+# install new apt sources list file
+cat >"$(etc_apt_sources_list_d)/$(echo "${here}" | tr -s '/' '_').list" <<EOF
+deb [trusted=yes] file://${here} ./
+EOF
+
+# update apt to make it aware of the new fake repo
+apt-get -yqo APT::Sandbox::User="$(whoami)" update
+
+readonly top_pkg_list="$(mktemp -t top_pkg_list.XXXXXX)"
+find "${here}" -maxdepth 1 -type f -name '*.deb' \
+    -exec dpkg-deb --show --showformat='${Package}\n' {} \; \
+    >"${top_pkg_list}"
+if ! [ "true" = "${requested_uninstall:-false}" ]; then
+    info "installing packages"
+    if [ -f "${here}/install-list.txt" ]; then
+        apt_install "${here}/install-list.txt"
+    else
+        apt_install "${top_pkg_list}"
+    fi
 else
-    build_megadeb
+    info "uninstalling packages"
+    if [ -f "${here}/uninstall-list.txt" ]; then
+        apt_uninstall "${here}/uninstall-list.txt"
+    else
+        apt_uninstall "${top_pkg_list}"
+    fi
+fi
+
+if ! [ "true" = "${requested_uninstall:-false}" ]; then
+    if [ -x "${here}/hooks/postinst" ]; then
+        "${here}/hooks/postinst"
+    fi
 fi
 
 exit "$?"
