detect distribution, infer version

diff --git a/mkrtlinux b/mkrtlinux
--- a/mkrtlinux
+++ b/mkrtlinux
@@ -10,8 +10,6 @@ readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
 
 readonly cachedir="${PWD}/cache.d"
 
-readonly default_version="4.16"
-
 log() { echo "${whatami}[$$]: $*" >&2; }
 error() { log "ERROR: $*"; }
 warning() { log "WARNING: $*"; }
@@ -41,8 +39,9 @@ Build a Debian package for a PREEMPTRT-patched linux kernel.
 
 Options:
 
-    -h            print this usage and return success
-    -V VERSION    patch and build VERSION (default: ${default_version})
+    -h                 print this usage and return success
+    -D DISTRIBUTION    override DISTRIBUTION (default: detected from host)
+    -V VERSION         patch and build VERSION (default: inferred from DISTRIBUTION)
 
 Examples:
 
@@ -50,7 +49,9 @@ Examples:
 
     \$ $0 
 
-    \$ $0 -V 5.6
+    \$ $0 -D bionic -V 4.16
+
+    \$ $0 -D focal -V 5.4
 
 Notes:
 
@@ -58,11 +59,44 @@ Notes:
 
     * VERSION must be 3.0 or later
 
+    * VERSION must be one listed here: https://www.kernel.org/pub/linux/kernel/projects/rt/
+
 EOF
 }
 
 vet_version() {
     echo "$1" | grep -Exm1 '[[:digit:]]+.[[:digit:]]+'
+}
+
+detect_distribution() {
+    if ! [ -f /etc/os-release ]; then
+        error "missing file: /etc/os-release"
+        return 1
+    fi
+    # shellcheck disable=SC2039
+    local result=""
+    if ! result="$(grep -Eom1 '^VERSION_CODENAME=[[:lower:]]+$' /etc/os-release)"; then
+        error "undefined VERSION_CODENAME: /etc/os-release"
+        return 1
+    fi
+    echo "${result#VERSION_CODENAME=}"
+}
+
+# $1 : distribution
+infer_version() {
+    # Use the version from the rt list that is nearest (without going under)
+    # that of the released version.
+    # https://www.kernel.org/pub/linux/kernel/projects/rt/
+    # https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions
+    case "$1" in
+        xenial) echo "4.4" ;;
+        bionic) echo "4.16" ;;
+        focal) echo "5.4" ;;
+        *)
+            error "unknown distribution: \"$1\""
+            return 1
+            ;;
+    esac
 }
 
 # $1 : uri
@@ -119,12 +153,13 @@ if [ -z "${DEBEMAIL:-}" ]; then
     die "undefined environement variable: DEBEMAIL"
 fi
 
-while getopts ":hV:" opt; do
+while getopts ":hD:V:" opt; do
     case "${opt}" in
         h)
             usage
             exit 0
             ;;
+        D) readonly distribution="${OPTARG}" ;;
         V)
             if ! version="$(vet_version "${OPTARG}")"; then
                 die "FAILURE: vet_version ${OPTARG}"
@@ -137,22 +172,38 @@ while getopts ":hV:" opt; do
 done
 shift "$((OPTIND - 1))"
 
+################################################################################
+
+# distribution
+if [ -n "${distribution:-}" ]; then
+    info "distribution: ${distribution}"
+elif distribution="$(detect_distribution)"; then
+    readonly distribution="${distribution}"
+    warning "detected distribution: ${distribution}"
+else
+    die "failed to get and/or detect distribution"
+fi
+
 # version
 if [ -n "${version:-}" ]; then
     info "version: ${version}"
+elif version="$(infer_version "${distribution}")"; then
+    readonly version="${version}"
+    warning "inferred version: ${version}"
 else
-    readonly version="${default_version}"
-    warning "defaulting version: ${version}"
+    die "failed to get and/or infer version"
 fi
 
 ################################################################################
 
+# get the index page
 readonly patch_index_uri="https://www.kernel.org/pub/linux/kernel/projects/rt/${version}/"
 info "patch_index_uri: ${patch_index_uri}"
 readonly patch_index_file="$(uri_dest "${patch_index_uri}")index.html"
 info "patch_index_file: ${patch_index_file}"
 wget_cache "${patch_index_uri}"
 
+# parse the index page to discover patch for desired version
 readonly patch_xz_basename="$(
     grep -Eo '[[:alnum:]_.-]+[.]patch[.]xz' "${patch_index_file}" \
         | sort -uV \
@@ -163,6 +214,7 @@ if [ -z "${patch_xz_basename}" ]; then
 fi
 info "patch_xz_basename: ${patch_xz_basename}"
 
+# get patch
 readonly patch_xz_uri="${patch_index_uri}${patch_xz_basename}"
 info "patch_xz_uri: ${patch_xz_uri}"
 readonly patch_xz_file="$(uri_dest "${patch_xz_uri}")"
@@ -210,6 +262,9 @@ unless_exists_eval "${linux_dir}/.patched" patch \
 
 make -C "${linux_dir}" olddefconfig
 
-make -C "${linux_dir}" deb-pkg "$@"
+# these variables are consumed within `scripts/package/builddeb`
+make \
+    KDEB_CHANGELOG_DIST="${distribution}" \
+    -C "${linux_dir}" deb-pkg "$@"
 
 exit "$?"
