ed mount-sshfs: shellcheck fixes

diff --git a/mount-sshfs b/mount-sshfs
--- a/mount-sshfs
+++ b/mount-sshfs
@@ -5,23 +5,22 @@
 set -euvx
 
 readonly this="$(readlink -f "$0")"
-readonly here="$(dirname "${this}")"
 readonly whatami="$(basename "${this}")"
 readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
 
-log() { echo "${whatami}[$$]: $@" >&2; }
-error() { log "ERROR: $@"; }
-warning() { log "WARNING: $@"; }
-info() { log "INFO: $@"; }
+log() { echo "${whatami}[$$]: $*" >&2; }
+error() { log "ERROR: $*"; }
+warning() { log "WARNING: $*"; }
+info() { log "INFO: $*"; }
 
 die() {
-    error "$@"
+    error "$*"
     usage >&2
     exit 1
 }
 
 cleanup() {
-    local status="$?"
+    status="$?"
     rm -rf "${tmpdir}" || true
     return "${status}"
 }
@@ -64,7 +63,7 @@ while getopts ":hu" opt; do
         \?) die "Invalid option: -${OPTARG}" ;;
     esac
 done
-shift "$((${OPTIND} - 1))"
+shift "$((OPTIND - 1))"
 
 if ! [ 1 -eq "$#" ]; then
     die "bad args"
@@ -78,13 +77,13 @@ if ! command -v sshfs >/dev/null 2>&1; then
     die "missing program: sshfs"
 fi
 
-if ! [ -n "${HOME:-}" ]; then
+if [ -z "${HOME:-}" ]; then
     warning "undefined \$HOME"
     if ! getent_passwd_all="$(getent passwd "$(id -u)")"; then
         die "FAILURE: getent passwd $(id -u)"
     fi
     getent_passwd_home="$(echo "${getent_passwd_all}" | cut -d: -f6)"
-    if ! [ -n "${getent_passwd_home}" ]; then
+    if [ -z "${getent_passwd_home}" ]; then
         die "bad getent passwd: ${getent_passwd_all}"
     fi
     export HOME="${getent_passwd_home}"
