wrap-catkin shellcheck fixes

diff --git a/wrap-catkin b/wrap-catkin
--- a/wrap-catkin
+++ b/wrap-catkin
@@ -9,13 +9,13 @@ readonly here="$(dirname "${this}")"
 readonly whatami="$(basename "${this}")"
 readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
 
-log() { echo "${whatami}[$$]: $@" >&2; }
-error() { log "ERROR: $@"; }
-warning() { log "WARNING: $@"; }
-info() { log "INFO: $@"; }
+log() { echo "${whatami}[$$]: $*" >&2; }
+error() { log "ERROR: $*"; }
+warning() { log "WARNING: $*"; }
+info() { log "INFO: $*"; }
 
 die() {
-    error "$@"
+    error "$*"
     usage >&2
     exit 1
 }
@@ -62,9 +62,9 @@ while getopts ":h" opt; do
         \?) die "bad option: -${OPTARG}" ;;
     esac
 done
-shift "$((${OPTIND} - 1))"
+shift "$((OPTIND - 1))"
 
-catkin $@ \
+catkin "$@" \
     --no-color \
     --no-notify \
     --no-status \
